### ISSUE TITLE
missing .txt file?

### ISSUE THREAD

**Issue by jrdingwall** [Downes/gRSShopper#3]
After clicking "multisite" software error generated:
"Cannot open .//home/**********/public_html/cgi-bin/data/multisite.txt: No such file or directory at initialize.cgi line 169."

**Comment by x28de** [comment]
The two recommendations `Site cgi directory is: ./` and `Site CGI Directory /home/*******/public_html/cgi-bin` are not additive but alternative. I was happy with `./` i.e., one dot and one slash.

**Comment by Downes** [comment]
The original error was created by data in the config table in the sql upload
Pushed a changed to standardize data directory on ./data in order to correct that
Not ideal because I'd like people to be able to store this in other (more secure) locations
Also, there may be additional errors in the future because of this, if the data in the sql is inconsistent with the actual server configuration. I'll close for now tho.
